version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: 'root'
        command: [--server-id=1, --log-bin=/var/lib/mysql/mysql-bin.log, --binlog-format=row]

    working_directory: ~/mysql-events

    steps:
      - checkout

      - restore_cache:
          keys:
            - lib-dependencies-{{ checksum "package.json" }}
            - lib-dependencies-

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - save_cache:
          paths:
            - node_modules
          key: lib-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests/coverage
          command: |
            npm run coverage
            ./cc-test-reporter format-coverage -t lcov -o coverage.json coverage/lcov.info
            ./cc-test-reporter upload-coverage -i coverage.json
